import * as Dialog from '@radix-ui/react-dialog';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MapPin, Pencil, Plus, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { EmptyState, ErrorState, LoadingState } from '../../components/page-state';
import { Button, Card, Field, Input, PageHeader } from '../../components/ui';
import { api } from '../../lib/api';
import type { Address, AddressInput } from '../../types';

const schema = z.object({ label: z.string().trim().min(1, 'Label is required.'), line1: z.string().trim().min(5, 'Enter a complete address.'), city: z.string().trim().min(2), province: z.string().trim().min(2), postalCode: z.string().trim().min(5), isDefault: z.boolean() });

export default function AddressesPage() {
  const client = useQueryClient();
  const [editing, setEditing] = useState<Address | null | undefined>(undefined);
  const [message, setMessage] = useState('');
  const query = useQuery({ queryKey: ['addresses'], queryFn: () => api.get<Address[]>('/customer/addresses') });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/customer/addresses/${id}`), onSuccess: async () => { setMessage('Address deleted.'); await client.invalidateQueries({ queryKey: ['addresses'] }); } });
  return <><PageHeader eyebrow="Address book" title="Sender and return addresses" description="Shipment addresses are snapshotted at creation, so editing this book never rewrites shipment history." action={<Button onClick={() => setEditing(null)}><Plus className="size-4" />Add address</Button>} />{message && <p role="status" className="rounded-control bg-success/10 p-3 text-sm text-success">{message}</p>}{query.isLoading && <LoadingState label="Loading addresses" />}{query.isError && <ErrorState error={query.error} onRetry={() => void query.refetch()} />}{query.data?.length === 0 && <EmptyState title="No saved addresses" description="Add a sender address before creating a shipment." action={<Button onClick={() => setEditing(null)}>Add address</Button>} />}{query.data && query.data.length > 0 && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.map((address) => <Card key={address.id} className="p-5"><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-control bg-brand/10 text-brand"><MapPin className="size-5" /></span>{address.isDefault && <span className="rounded-full bg-info/10 px-2.5 py-1 text-xs font-bold text-info">Default</span>}</div><h2 className="mt-4 font-bold">{address.label}</h2><address className="mt-2 text-sm not-italic leading-6 text-muted">{address.line1}<br />{address.city}, {address.province}<br />{address.postalCode}</address><div className="mt-5 flex gap-2 border-t border-line pt-4"><Button variant="secondary" onClick={() => setEditing(address)}><Pencil className="size-4" />Edit</Button><Button variant="ghost" className="text-danger" disabled={remove.isPending} onClick={() => { if (window.confirm(`Delete ${address.label}?`)) remove.mutate(address.id); }}><Trash2 className="size-4" />Delete</Button></div></Card>)}</div>}<AddressDialog value={editing} onOpenChange={(open) => { if (!open) setEditing(undefined); }} onSaved={async () => { setEditing(undefined); setMessage('Address saved.'); await client.invalidateQueries({ queryKey: ['addresses'] }); }} /></>;
}

function AddressDialog({ value, onOpenChange, onSaved }: { value: Address | null | undefined; onOpenChange: (open: boolean) => void; onSaved: () => Promise<void> }) {
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<AddressInput>({ resolver: zodResolver(schema), defaultValues: { label: '', line1: '', city: '', province: '', postalCode: '', isDefault: false } });
  const [serverError, setServerError] = useState('');
  useEffect(() => { if (value !== undefined) reset(value ?? { label: '', line1: '', city: '', province: '', postalCode: '', isDefault: false }); }, [value, reset]);
  const submit = handleSubmit(async (input) => { setServerError(''); try { if (value) await api.put(`/customer/addresses/${value.id}`, input); else await api.post('/customer/addresses', input); await onSaved(); } catch (error) { setServerError(error instanceof Error ? error.message : 'Could not save address.'); } });
  return <Dialog.Root open={value !== undefined} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-canvas/75 backdrop-blur-sm" /><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-card border border-line bg-surface p-6 shadow-2xl"><div className="flex items-start justify-between"><div><Dialog.Title className="text-xl font-bold">{value ? 'Edit address' : 'Add address'}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-muted">Used as a sender and return location.</Dialog.Description></div><Dialog.Close asChild><Button variant="ghost" className="size-11 px-0" aria-label="Close"><X className="size-5" /></Button></Dialog.Close></div><form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={submit}><div className="sm:col-span-2"><Field label="Label" htmlFor="address-label" error={errors.label?.message}><Input id="address-label" {...register('label')} /></Field></div><div className="sm:col-span-2"><Field label="Street address" htmlFor="address-line" error={errors.line1?.message}><Input id="address-line" {...register('line1')} /></Field></div><Field label="City" htmlFor="address-city" error={errors.city?.message}><Input id="address-city" {...register('city')} /></Field><Field label="Province" htmlFor="address-province" error={errors.province?.message}><Input id="address-province" {...register('province')} /></Field><Field label="Postal code" htmlFor="address-postal" error={errors.postalCode?.message}><Input id="address-postal" {...register('postalCode')} /></Field><label className="flex min-h-11 items-center gap-3 self-end text-sm font-semibold"><input className="size-5 accent-brand" type="checkbox" {...register('isDefault')} />Default address</label>{serverError && <p className="sm:col-span-2 text-sm text-danger" role="alert">{serverError}</p>}<div className="flex justify-end gap-2 border-t border-line pt-4 sm:col-span-2"><Dialog.Close asChild><Button variant="secondary">Cancel</Button></Dialog.Close><Button type="submit" disabled={isSubmitting}>{isSubmitting ? 'Saving…' : 'Save address'}</Button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
