<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MyPost.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\MyPost.Application\MyPost.Application.csproj" />
    <ProjectReference Include="..\..\src\MyPost.Infrastructure\MyPost.Infrastructure.csproj" />
  </ItemGroup>
</Project>
